### ISSUE TITLE
Write good meta descriptions for all main pages

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#397]
To do

- [X] Home page - updated homepage to include a lead text and h1 and a subscribe inline so that Google might be more likely to pick up the relevant text
- [X] Search page
- [X] About page — need to improve and organise the About page content better generally so that it actually uses the one in the code.
- [X] Big Ideas Little Pictures page
- [ ] Search
- [x] Categories
  - [x] Each individual category
- [x] Archive
- [x] List
- [x] Licence
- [x] Each category should have a good link back to all categories (breadcrumbs)

New category pages
![Image](https://github.com/user-attachments/assets/569f8aeb-83e8-4c78-93d1-ea1287d6388d)

New home at the top:
![Image](https://github.com/user-attachments/assets/8b0fd0c2-9ef1-4a70-817e-4e63ffae21d3)

Start:

Oh my gosh. Must sort.
![Image](https://github.com/user-attachments/assets/3b3d645f-41b9-43b6-97c3-3806f0344def)

![Image](https://github.com/user-attachments/assets/ab6cb18d-6701-42fd-ac03-3d718375ef4e)
